[
  import_deps: [:ecto, :phoenix],
  plugins: [Phoenix.LiveView.HTMLFormatter],
  inputs: [
    "*.{ex,exs}",
    "priv/*/seeds.exs",
    "{config,lib,test}/**/*.{ex,exs}",
    "{lib,priv}/**/*.{heex,leex}"
  ],
  line_length: 120,
  locals_without_parens: [
    # Ecto
    field: 2,
    field: 3,
    belongs_to: 2,
    belongs_to: 3,
    has_one: 2,
    has_one: 3,
    has_many: 2,
    has_many: 3,
    embeds_one: 2,
    embeds_one: 3,
    embeds_many: 2,
    embeds_many: 3,
    many_to_many: 2,
    many_to_many: 3,
    add: 2,
    add: 3,
    remove: 1,
    remove: 2,
    create: 1,
    create: 2,
    create_if_not_exists: 1,
    create_if_not_exists: 2,
    alter: 2,
    drop: 1,
    drop_if_exists: 1,
    rename: 2,
    rename: 3,
    unique_index: 2,
    unique_index: 3,
    index: 2,
    index: 3,
    execute: 1,
    execute: 2,

    # Phoenix
    plug: 1,
    plug: 2,
    action_fallback: 1,
    render: 2,
    render: 3,
    render: 4,
    redirect: 2,
    resources: 2,
    resources: 3,
    resources: 4,
    get: 2,
    get: 3,
    get: 4,
    post: 2,
    post: 3,
    post: 4,
    put: 2,
    put: 3,
    put: 4,
    patch: 2,
    patch: 3,
    patch: 4,
    delete: 2,
    delete: 3,
    delete: 4,
    forward: 2,
    forward: 3,
    forward: 4,
    pipe_through: 1,
    scope: 2,
    scope: 3,

    # LiveView
    assign: 2,
    assign: 3,
    assign_new: 3,
    update: 3,

    # Custom DSL for Ledger
    define_account: 2,
    define_accounts: 1,
    account: 2,
    group: 2,
    transaction: 1,
    entry: 1,
    position: 2,
    position: 3,
    template: 2,
    template: 3,
    apply_template: 2,
    validate: 2
  ]
]
