# Tideland Ledger Configuration
# This file contains configuration for the Tideland Ledger application
# All settings here override the default values

[database]
# SQLite database settings
journal_mode = "WAL"
synchronous = "NORMAL"
busy_timeout = 5000

[auth]
# Authentication and authorization settings
password_min_length = 12
session_timeout_minutes = 30
max_failed_attempts = 5
lockout_duration_minutes = 15
password_algorithm = "argon2"
session_sliding_expiration = true
session_single_per_user = false
force_password_change_on_first_login = true
# admin_password = "your-secure-password-here"  # Uncomment to set admin password

[accounts]
# Account management settings
max_depth = 6
recent_transaction_days = 30

[amount]
# Currency and amount calculation settings
default_currency = "EUR"
precision = 2

[transactions]
# Transaction processing settings
allow_backdated = true
max_backdate_days = 365
max_positions = 100

[periods]
# Period closing settings
closing_enabled = true
closable_types = ["month", "quarter", "year"]

[import]
# Data import settings
max_file_size = 10485760  # 10 MB
batch_size = 100

[export]
# Data export settings
formats = ["csv", "json"]

[ui]
# User interface settings
items_per_page = 50
session_timeout = 1800  # 30 minutes in seconds
date_format = "%d.%m.%Y"
datetime_format = "%d.%m.%Y %H:%M"
